import { Container, CssBaseline, GlobalStyles } from "@mui/material";
import Head from "next/head";
import React from "react";

import { Header } from "~/components/Header";

export interface PageProps {
  title: string;
}
export const Page: React.FC<PageProps> = ({ title, children }) => {
  return (
    <>
      <CssBaseline />
      <GlobalStyles styles={{ ul: { margin: 0, padding: 0, listStyle: "none" } }} />

      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <Container sx={{ p: 6, display: "flex", justifyContent: "center" }}>{children}</Container>
    </>
  );
};
