import { Box, Container, CssBaseline } from "@mui/material";
import type { NextPage } from "next";
import Head from "next/head";

import { SignUp } from "../components/SignUp";

const Home: NextPage = () => {
  return (
    <>
      <CssBaseline />

      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container sx={{ p: 6, display: "flex", justifyContent: "center" }}>
        <Box sx={{ border: 1, borderColor: "grey.300", borderRadius: 2, p: 3 }} maxWidth={500}>
          <SignUp />
        </Box>
      </Container>
    </>
  );
};

export default Home;
